import os


def time_to_str(time):
    hours = int(time // 3600)
    minutes = int((time % 3600) // 60)
    seconds = time % 60
    return f'{hours:02d}:{minutes:02d}:{seconds:06.2f}' # 在Aegisub只能读取到两位小数，VAD也是只保留两位，影响不大

def mask2ass(mask, ass_path):
	with open(ass_path, 'w', encoding='utf-8') as f:
		# 文件头
		f.write('[Script Info]\n')
		f.write('; Script generated by mask fix tools\n; https://github.com/KakaruHayate/mask_fix_tools\n')
		f.write('Title: Default Aegisub file\n')
		f.write('ScriptType: v4.00+\n')
		f.write('\n[Aegisub Project Garbage]\n')
		f.write('Audio File: audio.wav\n')
		f.write('\n[V4+ Styles]\n')
		f.write('Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n')
		f.write('Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n')
		f.write('\n[Events]\n')
		f.write('Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n')
		
		for start, end in mask:
			start_time = time_to_str(start)
			end_time = time_to_str(end)
			f.write(f"Dialogue: 0,{start_time},{end_time},Default,,0,0,0,,\n")